spring:
  mvc:
    static-path-pattern: '/resources/**'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    password: password
    username: postgres
server:
  port: 8086
logging:
  level:
    root: INFO
    org:
      springframework: INFO
springdoc:
  version: 1
  description: This is an API for MessageScheduler. You can find out more about it at [`github`](https://github.com/aNNufriy/message-scheduler).
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs