version: '3.3'
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=inventory
    ports:
      - 5434:5432
  postgresqltest:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=inventory
    ports:
      - 5435:5432